# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

agent:
  pool: MyHostedVM

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Microsoft Azure Enterprise (83cc3e46-0000-4be1-a33f-f757490dcebc)'
    KeyVaultName: 'petclinic-creds'
    SecretsFilter: '*'
    RunAsPreJob: false
