apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  my.jdbc.username: {{ .Values.jdbcusername }}
  my.jdbc.password: {{ .Values.jdbcpassword }}  
  my.jdbc.url: {{ .Values.jdbcurl }}
